"use client";

import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";

type TrustProfile = {
  name: string;
  pan: string;
  urn: string;
  approvalNumber: string;
  address: string;
  email: string;
  phone: string;
};

function currentTaxYear() {
  const parts = new Intl.DateTimeFormat("en-US", { timeZone: "Asia/Kolkata", year: "numeric", month: "numeric" }).formatToParts(new Date());
  const year = Number(parts.find((part) => part.type === "year")?.value);
  const month = Number(parts.find((part) => part.type === "month")?.value);
  const start = month >= 4 ? year : year - 1;
  return `${start}-${String((start + 1) % 100).padStart(2, "0")}`;
}

async function fetchInventory(year: string) {
  const response = await fetch(`/api/admin/80g/pre-arns?taxYear=${encodeURIComponent(year)}`);
  const data = await response.json();
  if (!response.ok || !data.success) throw new Error(data.error || "Could not load Pre-ARNs.");
  return data;
}

export function PreArnManager() {
  const [taxYear, setTaxYear] = useState(currentTaxYear);
  const [profile, setProfile] = useState<TrustProfile>({ name: "", pan: "", urn: "", approvalNumber: "", address: "", email: "", phone: "" });
  const [arnsText, setArnsText] = useState("");
  const [entries, setEntries] = useState<Array<{ arn: string; status: string }>>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  const load = useCallback(async (year: string, showLoading = true) => {
    if (showLoading) setLoading(true);
    try {
      const data = await fetchInventory(year);
      setProfile(data.profile);
      setEntries(data.entries);
      setError("");
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : "Could not load Pre-ARNs.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    let active = true;
    fetchInventory(currentTaxYear())
      .then((data) => {
        if (!active) return;
        setProfile(data.profile);
        setEntries(data.entries);
      })
      .catch((loadError) => { if (active) setError(loadError instanceof Error ? loadError.message : "Could not load Pre-ARNs."); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, []);

  const saveProfile = async (event: React.FormEvent) => {
    event.preventDefault();
    setBusy(true);
    setError("");
    setMessage("");
    try {
      const response = await fetch("/api/admin/80g/pre-arns", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ taxYear, profile }),
      });
      const data = await response.json();
      if (!response.ok || !data.success) throw new Error(data.error || "Could not save Trust details.");
      setMessage("Trust receipt details saved.");
    } catch (saveError) {
      setError(saveError instanceof Error ? saveError.message : "Could not save Trust details.");
    } finally {
      setBusy(false);
    }
  };

  const importArns = async (event: React.FormEvent) => {
    event.preventDefault();
    setBusy(true);
    setError("");
    setMessage("");
    try {
      const arns = arnsText.split(/[\r\n,;]+/).map((value) => value.trim().replace(/^['"]|['"]$/g, "")).filter((value) => value && !/pre.?acknowledgement|serial.?no|^arn$/i.test(value));
      const response = await fetch("/api/admin/80g/pre-arns", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ taxYear, arns }),
      });
      const data = await response.json();
      if (!response.ok || !data.success) throw new Error(data.error || "Could not import Pre-ARNs.");
      setArnsText("");
      setMessage(`${arns.length} Pre-ARN${arns.length === 1 ? "" : "s"} imported for tax year ${taxYear}.`);
      await load(taxYear);
    } catch (importError) {
      setError(importError instanceof Error ? importError.message : "Could not import Pre-ARNs.");
    } finally {
      setBusy(false);
    }
  };

  const setField = (key: keyof TrustProfile, value: string) => setProfile((current) => ({ ...current, [key]: value }));

  return (
    <section className="rounded-lg border border-border bg-surface p-6 space-y-6">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h2 className="text-xl font-serif text-maroon">Pre-ARN manual receipt setup</h2>
          <p className="mt-1 max-w-3xl text-sm text-muted">Import the numbers generated by the Income Tax e-Filing portal and enter the Trust details to show on manual receipts. These are not Form 114 certificates; Form 113 still must be filed and the official Form 114 issued afterward.</p>
        </div>
        <label className="text-sm text-muted">Tax year
          <input value={taxYear} onChange={(event) => setTaxYear(event.target.value)} onBlur={() => { if (/^\d{4}-\d{2}$/.test(taxYear)) void load(taxYear); }} pattern="\d{4}-\d{2}" className="ml-2 w-28 rounded-md border border-border bg-background px-3 py-2 font-mono text-text" aria-label="Tax year" />
        </label>
      </div>

      {error && <p role="alert" className="rounded-md bg-red/10 p-3 text-sm text-red">{error}</p>}
      {message && <p role="status" className="rounded-md bg-success/10 p-3 text-sm text-success">{message}</p>}

      <form onSubmit={saveProfile} className="space-y-4">
        <h3 className="font-medium text-maroon">Trust details printed on receipts</h3>
        <div className="grid gap-4 sm:grid-cols-2">
          {([
            ["name", "Trust legal name"], ["pan", "Trust PAN"], ["urn", "Unique Registration Number (URN)"],
            ["approvalNumber", "80G approval reference"], ["email", "Trust compliance email"], ["phone", "Trust phone"],
          ] as Array<[keyof TrustProfile, string]>).map(([key, label]) => (
            <label key={key} className="text-sm text-muted">{label}
              <input required value={profile[key]} onChange={(event) => setField(key, event.target.value)} className="mt-1 block w-full rounded-md border border-border bg-background px-3 py-2 text-text" />
            </label>
          ))}
        </div>
        <label className="block text-sm text-muted">Registered address
          <textarea required rows={2} value={profile.address} onChange={(event) => setField("address", event.target.value)} className="mt-1 block w-full rounded-md border border-border bg-background px-3 py-2 text-text" />
        </label>
        <Button type="submit" disabled={busy || loading}>{busy ? "Saving..." : "Save Trust receipt details"}</Button>
      </form>

      <form onSubmit={importArns} className="space-y-3 border-t border-border pt-5">
        <div className="flex items-center justify-between gap-4">
          <h3 className="font-medium text-maroon">Import portal-issued Pre-ARNs</h3>
          <span className="text-xs text-muted">{loading ? "Loading…" : `${entries.length} imported · ${entries.filter((entry) => entry.status === "AVAILABLE").length} available`}</span>
        </div>
        <textarea rows={4} value={arnsText} onChange={(event) => setArnsText(event.target.value)} placeholder="Paste the Pre-ARN column from the portal export (one per line or CSV). Up to 1,000 per import." className="block w-full rounded-md border border-border bg-background px-3 py-2 font-mono text-sm text-text" />
        <Button type="submit" disabled={busy || loading || !arnsText.trim()}>{busy ? "Importing..." : "Import Pre-ARNs"}</Button>
        {entries.length > 0 && <div className="max-h-36 overflow-auto rounded-md border border-border text-xs"><table className="w-full"><thead className="sticky top-0 bg-cream"><tr><th className="p-2 text-left">Pre-ARN</th><th className="p-2 text-left">Inventory status</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.arn} className="border-t border-border"><td className="p-2 font-mono">{entry.arn}</td><td className="p-2">{entry.status}</td></tr>)}</tbody></table></div>}
      </form>
    </section>
  );
}
