"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { T } from "@/components/i18n/t";
import { useI18n } from "@/lib/i18n";

export default function TaxExemption80GPage() {
  const { t } = useI18n();
  const [form, setForm] = useState({
    receiptNumber: "",
    email: "",
    donorName: "",
    pan: "",
    addressLine1: "",
    addressLine2: "",
    city: "",
    state: "",
    pincode: "",
  });
  const [status, setStatus] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setStatus("loading");
    setError(null);
    const res = await fetch("/api/80g", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(form),
    });
    const data = await res.json();
    if (!data.success) {
      setStatus("error");
      setError(data.error?.message || "Verification failed. Please check your details.");
      return;
    }
    setStatus("done");
  };

  return (
    <div className="container-app py-16 max-w-3xl">
      <h1 className="text-4xl font-serif text-maroon">{t("80G Tax Exemption", undefined, { isSensitive: true })}</h1>
      <p className="mt-4 text-muted text-lg">
        {t("Submit your PAN and address details for statutory donation reporting and certificate issuance for eligible donations. For tax year 2026-27 onward, the Trust reports eligible donations in Form 113 and issues the official Form 114 certificate after it is generated by the Income Tax e-Filing portal.", undefined, { isSensitive: true })}
      </p>

      <div className="mt-10">
        {status === "done" ? (
          <div className="bg-success/10 border border-success/20 p-8 rounded-lg text-center">
            <h2 className="text-2xl text-success font-serif mb-2">{t("Information Submitted Successfully")}</h2>
            <p className="text-muted">
              {t("We have securely received your donation tax information. The Trust will verify it and report eligible donations through the applicable statutory process. For tax year 2026-27 onward, the official Form 114 certificate is generated after Form 113 is filed on the Income Tax e-Filing portal; the Trust will email it when available.")}
            </p>
            <Button className="mt-6" onClick={() => setStatus("idle")}>{t("Submit Another")}</Button>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="space-y-6 bg-surface p-8 rounded-xl border border-border shadow-[var(--shadow-soft)]">
            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-medium mb-1">{t("Donation Receipt Number *")}</label>
                <input
                  required
                  placeholder="e.g. RCT-12345678"
                  value={form.receiptNumber}
                  onChange={e => setForm({...form, receiptNumber: e.target.value})}
                  className="w-full rounded-lg border border-border px-4 py-2.5 bg-background text-sm"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">{t("Email Address *")}</label>
                <input
                  required
                  type="email"
                  placeholder="Email used for donation"
                  value={form.email}
                  onChange={e => setForm({...form, email: e.target.value})}
                  className="w-full rounded-lg border border-border px-4 py-2.5 bg-background text-sm"
                />
              </div>
            </div>

            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-medium mb-1">{t("Full Name (as per PAN) *")}</label>
                <input
                  required
                  value={form.donorName}
                  onChange={e => setForm({...form, donorName: e.target.value})}
                  className="w-full rounded-lg border border-border px-4 py-2.5 bg-background text-sm uppercase"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">{t("PAN Number *")}</label>
                <input
                  required
                  placeholder="ABCDE1234F"
                  value={form.pan}
                  onChange={e => setForm({...form, pan: e.target.value.toUpperCase()})}
                  className="w-full rounded-lg border border-border px-4 py-2.5 bg-background text-sm uppercase"
                  maxLength={10}
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium mb-1">{t("Address Line 1 *")}</label>
              <input
                required
                value={form.addressLine1}
                onChange={e => setForm({...form, addressLine1: e.target.value})}
                className="w-full rounded-lg border border-border px-4 py-2.5 bg-background text-sm"
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium mb-1">{t("Address Line 2 (Optional)")}</label>
              <input
                value={form.addressLine2}
                onChange={e => setForm({...form, addressLine2: e.target.value})}
                className="w-full rounded-lg border border-border px-4 py-2.5 bg-background text-sm"
              />
            </div>

            <div className="grid grid-cols-3 gap-6">
              <div>
                <label className="block text-sm font-medium mb-1">{t("City *")}</label>
                <input
                  required
                  value={form.city}
                  onChange={e => setForm({...form, city: e.target.value})}
                  className="w-full rounded-lg border border-border px-4 py-2.5 bg-background text-sm"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">{t("State *")}</label>
                <input
                  required
                  value={form.state}
                  onChange={e => setForm({...form, state: e.target.value})}
                  className="w-full rounded-lg border border-border px-4 py-2.5 bg-background text-sm"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">{t("Pincode *")}</label>
                <input
                  required
                  maxLength={6}
                  value={form.pincode}
                  onChange={e => setForm({...form, pincode: e.target.value})}
                  className="w-full rounded-lg border border-border px-4 py-2.5 bg-background text-sm"
                />
              </div>
            </div>

            {error && <div className="p-4 bg-red/10 text-red text-sm rounded-lg border border-red/20">{error}</div>}

            <Button type="submit" size="lg" className="w-full" disabled={status === "loading"}>
              {status === "loading" ? t("Submitting...") : t("Submit 80G Information")}
            </Button>
            
            <p className="text-xs text-muted text-center mt-4">
              {t("By submitting this form, you consent to Shri Nityanikunj Trust using your PAN and address strictly for statutory donation reporting and certificate issuance (Form 113/114 for tax year 2026-27 onward, or the applicable earlier forms).", undefined, { isSensitive: true })}
            </p>
          </form>
        )}
      </div>
    </div>
  );
}
